# Generated by Django 3.2.13 on 2022-04-22 01:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 1, 48, 8, 219588, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ExpertiseHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financeTitle', models.CharField(help_text='Title', max_length=200)),
                ('financeText', models.TextField()),
                ('restructureTitle', models.CharField(help_text='Title', max_length=200)),
                ('restructureText', models.TextField()),
                ('economicTitle', models.CharField(help_text='Title', max_length=200)),
                ('economicText', models.TextField()),
                ('litigationTitle', models.CharField(help_text='Title', max_length=200)),
                ('litigationText', models.TextField()),
                ('strategicTitle', models.CharField(help_text='Title', max_length=200)),
                ('strategicText', models.TextField()),
                ('technicalTitle', models.CharField(help_text='Title', max_length=200)),
                ('technicalText', models.TextField()),
                ('createDate', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 1, 48, 8, 220093, tzinfo=utc))),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
