# Generated by Django 3.2.13 on 2022-04-22 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220422_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertisehome',
            old_name='economicText',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='economicTitle',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='financeText',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='litigationText',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='litigationTitle',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='publishedDate',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='restructureText',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='restructureTitle',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='strategicText',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='strategicTitle',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='technicalText',
        ),
        migrations.RemoveField(
            model_name='expertisehome',
            name='technicalTitle',
        ),
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 2, 6, 4, 463168, tzinfo=utc)),
        ),
    ]
