# Generated by Django 3.2.13 on 2022-04-22 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220422_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 751819, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 752219, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertise',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertisehomeeconomic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 748473, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertisehomeeconomic',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertisehomefinance',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 747583, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertisehomefinance',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertisehomelitigation',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 748873, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertisehomelitigation',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertisehomerestructure',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 748064, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertisehomerestructure',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertisehomestrategic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 749276, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertisehomestrategic',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertisehometechnical',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 749676, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertisehometechnical',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 747165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 23, 15, 750118, tzinfo=utc)),
        ),
    ]
