# Generated by Django 3.2.13 on 2022-04-22 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220422_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 397344, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 402079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 402479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomeeconomic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 398651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomefinance',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 397766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomelitigation',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 399052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomerestructure',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 398249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomestrategic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 399460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehometechnical',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 399862, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 18, 39, 38, 400304, tzinfo=utc)),
        ),
    ]
