# Generated by Django 3.2.13 on 2022-04-22 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20220422_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 850768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 855988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 856403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomeeconomic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 852376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomefinance',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 851338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomelitigation',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 852806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomerestructure',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 851933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomestrategic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 853247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehometechnical',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 853673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 854154, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ExpertiseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('text', models.TextField()),
                ('createDate', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 856859, tzinfo=utc))),
                ('publishedDate', models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 25, 3, 856877, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
