# Generated by Django 3.2.13 on 2022-04-22 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220422_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 699236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 704438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 704846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 705319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 705336, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomeeconomic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 700808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomefinance',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 699772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomelitigation',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 701244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomerestructure',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 700363, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehomestrategic',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 701656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisehometechnical',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 702089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 42, 6, 702564, tzinfo=utc)),
        ),
    ]
