# Generated by Django 3.2.13 on 2022-04-24 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220422_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisehomefinance',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expertisehomelitigation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expertisehomerestructure',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expertisehomestrategic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expertisehometechnical',
            name='author',
        ),
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 23, 15, 1, 716593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 23, 15, 1, 718190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 23, 15, 1, 718592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 23, 15, 1, 719000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 23, 15, 1, 719017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 23, 15, 1, 717115, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ExpertiseHomeEconomic',
        ),
        migrations.DeleteModel(
            name='ExpertiseHomeFinance',
        ),
        migrations.DeleteModel(
            name='ExpertiseHomeLitigation',
        ),
        migrations.DeleteModel(
            name='ExpertiseHomeRestructure',
        ),
        migrations.DeleteModel(
            name='ExpertiseHomeStrategic',
        ),
        migrations.DeleteModel(
            name='ExpertiseHomeTechnical',
        ),
    ]
