# Generated by Django 3.2.13 on 2022-04-27 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220424_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 1, 0, 25, 108896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 1, 0, 25, 110477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 1, 0, 25, 110932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 1, 0, 25, 111364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 1, 0, 25, 111382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 1, 0, 25, 109393, tzinfo=utc)),
        ),
    ]
