# Generated by Django 3.2.13 on 2022-04-28 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220427_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 31, 24, 681551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 31, 24, 683178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 31, 24, 683615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 31, 24, 684008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 31, 24, 684027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 31, 24, 682051, tzinfo=utc)),
        ),
    ]
