# Generated by Django 3.2.13 on 2022-04-28 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220428_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthome',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 34, 0, 227301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 34, 0, 229195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 34, 0, 229670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 34, 0, 230389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expertisedetail',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 34, 0, 230430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 34, 0, 227794, tzinfo=utc)),
        ),
    ]
